# xp-forge/mustache

language: php

php:
  - 5.4
  - 5.5
  - 5.6

before_script:
  - wget 'https://github.com/xp-framework/xp-runners/releases/download/v5.0.0/setup' -O - | php
  - wget 'https://github.com/xp-framework/core/releases/download/v6.0.0beta1/xp-rt-6.0.0beta1.xar'
  - wget 'https://github.com/xp-forge/json/releases/download/v0.8.3/xp-json-0.8.4.xar'
  - ls -1 *.xar > boot.pth
  - echo "[runtime]" >> xp.ini
  - echo "date.timezone=Europe/Berlin" >> xp.ini

script:
  - wget 'https://github.com/mustache/spec/archive/master.zip' -O master.zip
  - unzip master.zip && rm master.zip
  - ./unittest com.github.mustache.unittest.** -a spec-master/specs/

before_deploy:
  - export REL=`echo $TRAVIS_TAG | sed -e 's/^v//g'`
  - export MOD=`echo $TRAVIS_REPO_SLUG | cut -d '/' -f 2`
  - wget https://github.com/xp-framework/build/releases/download/v3.0.0alpha2/travis.xar
  - ./xp -cp travis.xar net.xp_framework.build.Travis . $MOD $REL
  - cat glue.json

deploy:
  provider: releases
  file:
    - xp-$MOD-$REL.xar
    - xp-$MOD-test-$REL.xar
    - glue.json
  skip_cleanup: true
  on:
    repo: $TRAVIS_REPO_SLUG
    tags: true
    all_branches: true
    php: 5.4
  api_key:
    secure: "n0G96ao0ZLU/qnSu6iar2nJ98H6szd+iyXl3BicoHS1+Za2FqBrP/EFl27Gz3E/yvEUhoajGADv5iqdJlCCVJCqI9lQyWUOc3D7QBBIvjIo4Pk0n5FCTm+cZ50rXEpNYrmZ3qgMAjriZFylQSz6Gzze4RQgbKArijBs+fT4zFe0="
